### ISSUE TITLE
hd parameter set, but still allows me to login on a different domain

### ISSUE THREAD

**Issue by csamp516** [zquestz/omniauth-google-oauth2#220]
My `config/initializers/omniauth.rb` file looks something like:
```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV["GOOGLE_CLIENT_ID"], ENV["GOOGLE_CLIENT_SECRET"]
    {
      :hd => "mydomain.com"
    }
end
```
The URL sent to Google includes the `hd` parameter, but I am still able to log in using a different domain.

For now, I am checking the callback to verify the domain there (as suggested by Google).  Let me know if you need more info.

**Comment by zquestz** [comment]
Yeah if it is sent and they allow the login not much I can do in the library. What you are doing is valid, just check the response and fail the login that way.

**Comment by rkistner** [comment]
This issue bit me as well - I thought my site only allowed logins from one domain, when in fact it allowed any gmail account to log in.

If the check is not done in the library, the readme should be updated. Currently it says:

> `hd`: (Optional) Limit sign-in to a particular Google Apps hosted domain.

when in fact it's open to any domain.

I'm not sure how to do this with omniauth, but you have to check that `hash[:id_info][:id]` matches the requested `:hd` parameter, somewhere around here: https://github.com/zquestz/omniauth-google-oauth2/blob/master/lib/omniauth/strategies/google_oauth2.rb#L61

My current workaround: https://github.com/journeyapps/simple_admin_auth/blob/master/lib/simple_admin_auth/application.rb#L19-L27

**Comment by taylorbrooks** [comment]
When will this gem be cut?

**Comment by dwradcliffe** [comment]
Definitely good to validate, but sad that google suddenly stopped respecting that parameter.

**Comment by ajsharp** [comment]
@dwradcliffe Wait google stopped respecting the parameter? Was there a release about this somewhere? Or are you assuming since they're allowing the login despite the param being sent?

**Comment by dwradcliffe** [comment]
I'm assuming they stopped respecting the parameter because we didn't change anything on our end and originally it prevented the login, and now it doesn't.

**Comment by rkistner** [comment]
The parameter passed to Google has always been a client-side (UI) parameter only, not a security parameter. Even before they changed their UI it was possible to login with a different domain, if you knew how (it was either a change in the URL or in client-side form post parameters). Their new UI only makes it more obvious that you can switch accounts.

The checking of the response (added in 0.3.1 of this gem) is the only thing that actually provides security here.

**Comment by riyasyash** [comment]
@csamp516 , were you able to find a fix for this?

**Comment by rkistner** [comment]
@riyasyash This issue has been fixed long ago, part of 0.3.1.

**Comment by riyasyash** [comment]
@rkistner, but I am still facing this issue, I am not able to restrict users based on the email domain. :\
